apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
    processors:
      batch: {}
    exporters:
      logging:
        loglevel: debug
      jaeger:
        endpoint: "jaeger:14250"
        insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, jaeger]
