apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: demo-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend-read
  namespace: demo-app
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-bind
  namespace: demo-app
subjects:
  - kind: ServiceAccount
    name: frontend-sa
    namespace: demo-app
roleRef:
  kind: Role
  name: frontend-read
  apiGroup: rbac.authorization.k8s.io
